[program:octane]
process_name=%(program_name)s_%(process_num)02d
command=php artisan octane:start --server=frankenphp --max-requests=1000 --workers=auto
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/home/ronssrony/Documents/projects/people-pulse/storage/logs/octane.log
stopwaitsecs=3600
